# Generated by Django 2.2.12 on 2021-02-11 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Тема")),
                ("question1", models.TextField(verbose_name="Вопрос 1")),
                ("question2", models.TextField(verbose_name="Вопрос 2")),
                ("question3", models.TextField(verbose_name="Вопрос 3")),
                ("question4", models.TextField(verbose_name="Вопрос 4")),
                ("question5", models.TextField(verbose_name="Вопрос 5")),
                ("question6", models.TextField(verbose_name="Вопрос 6")),
            ],
            options={
                "verbose_name": "Вопросы",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("company", models.CharField(max_length=100, verbose_name="Компания")),
                ("partyID", models.PositiveIntegerField(verbose_name="Код каталога")),
                ("description", models.TextField(verbose_name="Описание (Вы купили)")),
                ("facture", models.PositiveIntegerField(verbose_name="Фактура")),
                ("factureDate", models.DateField(verbose_name="Дата фактуры")),
                ("phone", models.PositiveIntegerField(verbose_name="Телефон")),
                (
                    "phoneCompany",
                    models.PositiveIntegerField(verbose_name="Телефон Организации"),
                ),
                (
                    "phoneMobile",
                    models.PositiveIntegerField(verbose_name="Мобильный Телефон"),
                ),
                ("mail", models.EmailField(max_length=254)),
                ("rating1", models.PositiveIntegerField(verbose_name="Ответ 1")),
                ("unswer1", models.TextField(verbose_name="Примечание 1")),
                ("rating2", models.PositiveIntegerField(verbose_name="Ответ 2")),
                ("unswer2", models.TextField(verbose_name="Примечание 2")),
                ("rating3", models.PositiveIntegerField(verbose_name="Ответ 3")),
                ("unswer3", models.TextField(verbose_name="Примечание 3")),
                ("rating4", models.PositiveIntegerField(verbose_name="Ответ 4")),
                ("unswer4", models.TextField(verbose_name="Примечание 4")),
                ("rating5", models.PositiveIntegerField(verbose_name="Ответ 5")),
                ("unswer5", models.TextField(verbose_name="Примечание 5")),
                ("rating6", models.PositiveIntegerField(verbose_name="Ответ 6")),
                ("unswer6", models.TextField(verbose_name="Примечание 6")),
                (
                    "loadDate",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата загрузки"
                    ),
                ),
                ("url", models.SlugField(max_length=130, unique=True)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
