# Generated by Django 2.2.12 on 2021-02-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="title",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="polls.Questions",
                verbose_name="Тема опроса",
            ),
        ),
    ]
