# Generated by Django 2.2.12 on 2021-02-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_auto_20210211_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="facture",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фактура"
            ),
        ),
    ]
