# Generated by Django 2.2.12 on 2021-02-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_auto_20210215_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="factureDate",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Дата фактуры"
            ),
        ),
    ]
