# Generated by Django 2.2.12 on 2021-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_auto_20210215_0850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="phoneCompany",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Телефон Организации",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="phoneMobile",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Мобильный Телефон"
            ),
        ),
    ]
