# Generated by Django 2.2.12 on 2021-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_auto_20210215_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="anketa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Анкета"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="datePhone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Дата звонка"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="listPhone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Список обзвона"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="lucky",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Звонок успешен"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="timePhone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Время звонка"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="timesPhone",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Длительность звонка (в минутах)",
            ),
        ),
    ]
