# Generated by Django 2.2.12 on 2021-02-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_auto_20210216_0830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="partyID",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Код каталога"
            ),
        ),
    ]
