# Generated by Django 2.2.12 on 2021-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="facture",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Фактура"
            ),
        ),
    ]
