# Generated by Django 3.1.7 on 2021-04-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_auto_20210226_0637"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pages",
        ),
        migrations.AddField(
            model_name="users",
            name="rating7",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 7"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="rating8",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 8"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="rating9",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 9"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer7",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 7"),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer8",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 8"),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer9",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 9"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question6",
            field=models.TextField(verbose_name="Вопрос 9"),
        ),
    ]
