# Generated by Django 3.1.7 on 2021-04-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_auto_20210406_0416"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="question7",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 7"),
        ),
        migrations.AddField(
            model_name="questions",
            name="question8",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 8"),
        ),
        migrations.AddField(
            model_name="questions",
            name="question9",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 9"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question1",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 1"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question2",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 2"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question3",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 3"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question4",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 4"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question5",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 5"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question6",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 6"),
        ),
    ]
