# Generated by Django 3.1.7 on 2021-04-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0014_auto_20210406_0421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questions",
            options={
                "verbose_name": "Анкеты Transactional Survey",
                "verbose_name_plural": "Анкеты Transactional Survey",
            },
        ),
        migrations.AlterModelOptions(
            name="users",
            options={
                "verbose_name": "Результаты опросов",
                "verbose_name_plural": "Результаты опросов",
            },
        ),
    ]
