# Generated by Django 3.1.7 on 2021-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_auto_20210412_0456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
