# Generated by Django 3.1.7 on 2021-04-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0016_auto_20210421_0608"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="question10",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 10"),
        ),
        migrations.AddField(
            model_name="questions",
            name="question11",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 11"),
        ),
        migrations.AddField(
            model_name="questions",
            name="question12",
            field=models.TextField(blank=True, null=True, verbose_name="Вопрос 12"),
        ),
        migrations.AddField(
            model_name="users",
            name="rating10",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 10"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="rating11",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 11"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="rating12",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ответ 12"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer10",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 10"),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer11",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 11"),
        ),
        migrations.AddField(
            model_name="users",
            name="unswer12",
            field=models.TextField(blank=True, null=True, verbose_name="Примечание 12"),
        ),
    ]
